fix(themes): adds theme with animation duration in ms
lightning-js/ui-components pull request #114
Opened 2024-04-10 19:54 UTC by slhay28

## Description

adds theme with animation duration in ms

## Changes

## Testing

make sure everything looks right and theme values are coming through correctly.

2024-04-10 20:18 UTC, anthony9187 approved these changes

2024-04-10 20:36 UTC, chiefcll commented on src/packages/l3-ui-theme-base/theme.js
> +      duration: '250ms'
why a string with ms? Can't this just be a number?

2024-04-10 20:42 UTC, chiefcll requested changes
Fontstyle is broken too - should be fontWeight and previous duration would work = 0.5 = 500ms. You need to pass in a number to duration + delay

2024-04-16 10:58 UTC, chiefcll approved these changes

2024-04-16 10:59 UTC, merged